pessoa = ["pedro","duarte",29,1197]
pessoa.insert(2,"Daniel")
#pessoa.append("daniel")
print(pessoa)
pessoa.remove("Daniel")
print(pessoa)
pessoa.remove(29)
print(pessoa)
numero = pessoa.pop()
print(numero)
